route:
  receiver: 'mail'
  repeat_interval: 1m
  group_by: [ alertname ]


receivers:
  - name: 'mail'
    email_configs:
      - smarthost: 'smtp.gmail.com:465'
        auth_username: '.ajce.in'
        auth_password: ""
        from: '.ajce.in'
        to: '@gmail.com'