route:
  receiver: 'mail'
  repeat_interval: 1m
  group_by: [ alertname]


receivers:
  - name: 'mail'
    email_configs:
      - smarthost: 'smtp.gmail.com:465'
        auth_username: 'sajo2023b@mca.ajce.in'
        auth_password: "Sajo@000"
        from: 'sajo2023b@mca.ajce.in'
        to: 'saajosaam@gmail.com'