groups:
  - name: DemoAlerts
    rules:
      - alert: InstanceDown 
        expr: up{job="nodeexporter"} > 0
        for: 5s
        labels:
          severity: low
        annotations:
          summary: 'Alert with low severity.'

      - alert: InstanceDownCritical
        expr: up{job="services"} < 1 
        for: 10s
        labels:
          severity: high
        annotations:
          summary: 'Alert with high severity.'