groups:
  - name: DemoAlerts
    rules:
      - alert: InstanceDown 
        expr: up{job="nodeexporter"} > 0
        for: 5s
        labels:
          severity: low
        annotations:
          summary: 'Alert with low severity.'

      - alert: InstanceDownCritical
        expr: up{job="services"} < 1 
        for: 10s
        labels:
          severity: high
        annotations:
          summary: 'Alert with high severity.'
      
      - alert: HighCpuUtilization
        expr: 100 - (avg by (instance) (irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 90
        for: 10s
        labels:
          severity: high
        annotations:
          summary: 'High CPU Utilization detected.'