# global:
#   scrape_interval:     5s
#   evaluation_interval: 5s

# scrape_configs:
remote_write:
  - url: http://localhost:9009/api/v1/push

scrape_configs:
  - job_name: prometheus
    honor_labels: true
    static_configs:
      - targets: ["localhost:9090"]
  # - job_name: 'cadvisor'
  #   scrape_interval: 5s
  #   static_configs:
  #     - targets: ['cadvisor:8080']

  # - job_name: 'nodeexporter'
  #   scrape_interval: 5s
  #   static_configs:
  #     - targets: ['nodeexporter:9100']

  # - job_name: 'prometheus'
  #   scrape_interval: 10s
  #   static_configs:
  #     - targets: ['localhost:9090']

  # - job_name: 'loki'
  #   scrape_interval: 10s
  #   static_configs:
  #     - targets: ['loki:3100']

  # - job_name: 'promtail'
  #   scrape_interval: 10s
  #   static_configs:
  #     - targets: ['promtail:9080']


# alerting:
#   alertmanagers:
#     - scheme: http
#       static_configs:
#         - targets: [ 'alertmanager:9093' ]

# rule_files:
#   - ./alert.yml