metrics:
  wal_directory: /tmp/grafana-agent/wal

  configs:
    # - name: agent
    #   scrape_configs:
    #     - job_name: agent
    #       static_configs:
    #         - targets: ['nodeexporter:9100']
    #   remote_write:
    #     - url: http://mimir:9009/api/v1/push
  
    - name: loki
      scrape_configs:
        - job_name: loki
          static_configs:
            - targets: ['nodeexporter:9100']
      remote_write:
        - url: http://loki:3100/api/prom/push
